### ISSUE TITLE
Would like to contribute 

### ISSUE THREAD

**Issue by Bigocb** [dadencukillia/httpInfoServer-mod#1]
I am a developer in my day to day life and I would like to help out if you need. Question, are there particular features you are looking to add, I could pick one of those up. If not, I was thinking it could be nice to have a scoreboard or general word status output.

**Comment by dadencukillia** [comment]
Hello, of course I will be glad if you help and add new features. Although new features are a matter of time (while I'm waiting for new releases of minecraft), anyway I'm new to yarn api, you can add new features that you think are useful.

**Comment by Bigocb** [comment]
Thank you! I will get familiar with the code and go from there. If you think of anything specific, you'd like me to work on, even not adding features, let me know.

**Comment by dadencukillia** [comment]
That's great. I don't have any non-feature ideas in mind yet. Also, [code structure description](https://github.com/dadencukillia/httpInfoServer-mod?tab=readme-ov-file#code-structure) might help a bit.

**Comment by Bigocb** [comment]
Sounds good, I have an idea for a small change I would like to play around with. Would it be ok if you added me as a contributor so I can push a branch and open a PR when I am ready for you to review / discuss the proposed change?

**Comment by dadencukillia** [comment]
Okay, I have already sent a request for this.
